## name:      Cobalt2
## author:    Eugene Owak (@geneowak)
## license:   MIT
## reference: https://github.com/lalitmee/kitty-cobalt2/blob/master/cobalt2.conf

# The basic colors
foreground           =  #FFFFFF
background           =  #193549
selection-foreground =  #FFFFFF
selection-background =  #185294

# Cursor colors
cursor-color         =  #FFC600
cursor-text          =  #1C1C1C

# URL underline color when hovering with mouse
# url-color            =  #00AAFF

# Ghostty window border colors
# active-border-color   =  #00AAFF
# inactive-border-color =  #9E9E9E
# bell-border-color     =  #F2ED7F

# OS Window titlebar colors
# wayland-titlebar-color = system
# macos-titlebar-color   = system

# Tab bar colors
# active-tab-foreground   = #FFC600
# inactive-tab-background =  #185294
# inactive-tab-foreground = #FFFFFF
# active-tab-background   = #0050A4
# tab-bar-background      =    #193549

# Colors for marks (marked text in the terminal)
# mark1-foreground = #FFC600
# mark1-background = #3AD900
# mark2-foreground = #967EFB
# mark2-background = #00AAFF
# mark3-foreground = #FF628C
# mark3-background = #FF9A00

# The 16 terminal #88FF88#88FF88colors

# black
palette = 0=#1C1C1C
palette = 8=#9E9E9E

# red
palette = 1=#FF0000
palette = 9=#700009

# green
palette = 2=#3AD900
palette = 10=#88FF88

# yellow
palette = 3=#FFC600
palette = 11=#FF9A00

# cyan
palette = 6=#80FCFF
palette = 14=#8fbfdc

# magenta
palette = 5=#FF628C
palette = 13=#EE80E1

# blue
palette = 4=#00AAFF
palette = 12=#0050A4

# white
palette = 7=#FFFFFF
palette = 15=#BCBCBC
